services:
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: V7AVh7FWmUYTCWzY
      MONGO_INITDB_ROOT_PASSWORD: dYiQeJyd9Wv9K4Pz
    volumes:
      - ./.mongod:/data/db

  m3-server:
    container_name: m3-server
    image: m3-server
    build:
      context: .
      dockerfile: next.Dockerfile
    volumes:
      - ./data:/app/data
      - ./sandbox:/app/sandbox
    restart: always
    environment:
      MONGOURI: mongodb://V7AVh7FWmUYTCWzY:dYiQeJyd9Wv9K4Pz@mongodb
    depends_on:
      - mongodb
    ports:
      - 0.0.0.0:3000:3000

  m3-worker:
    container_name: m3-worker
    image: m3-worker
    build:
      context: .
      dockerfile: worker.Dockerfile
    entrypoint: 
      TARGET_HOST: http://m3-server:3000
    restart: always
    depends_on:
      - m3-server
      - mongodb