services:
  mongodb:
    image: mongodb:8.0.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=V7AVh7FWmUYTCWzY
      - MONGO_INITDB_ROOT_PASSWORD=dYiQeJyd9Wv9K4Pz
    volumes:
      - type: bind
        source: ./.mongod
        target: /data/db

  m3:
    build: .  
    environment:
      - MONGOURI=mongodb://V7AVh7FWmUYTCWzY:dYiQeJyd9Wv9K4Pz@mongodb
    depends_on:
      - mongodb
